name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to report a bug!

        Please fill out **all required fields** to help us reproduce and resolve your issue. Fields marked as required must be completed before submission.
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g. "When I click the Submit button, the page does not respond."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Step-by-step instructions on how to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: e.g. "A success message appears and I am redirected."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add links to screenshots or drag and drop images below. Type "N/A" if not applicable.
      placeholder: Drag images or provide links, or type "N/A"
    validations:
      required: true
  - type: input
    id: desktop_os
    attributes:
      label: Desktop OS
      description: Which operating system did you use? (Type "N/A" if not applicable)
      placeholder: e.g. "Windows 11", "macOS Sonoma", or "N/A"
    validations:
      required: true
  - type: input
    id: desktop_browser
    attributes:
      label: Desktop Browser
      description: Which browser and version did you use? (Type "N/A" if not applicable)
      placeholder: e.g. "Chrome 120", "Safari 17", or "N/A"
    validations:
      required: true
  - type: input
    id: desktop_version
    attributes:
      label: Desktop Version
      description: Desktop software or app version (Type "N/A" if not applicable)
      placeholder: e.g. "App v2.4.0" or "N/A"
    validations:
      required: true
  - type: input
    id: smartphone_device
    attributes:
      label: Smartphone Device
      description: Device name (Type "N/A" if not applicable)
      placeholder: e.g. "iPhone 14" or "N/A"
    validations:
      required: true
  - type: input
    id: smartphone_os
    attributes:
      label: Smartphone OS
      description: OS and version (Type "N/A" if not applicable)
      placeholder: e.g. "iOS 17.2" or "N/A"
    validations:
      required: true
  - type: input
    id: smartphone_browser
    attributes:
      label: Smartphone Browser
      description: Which browser/app and version (Type "N/A" if not applicable)
      placeholder: e.g. "Safari", "Chrome", or "N/A"
    validations:
      required: true
  - type: input
    id: smartphone_version
    attributes:
      label: Smartphone App Version
      description: App/browser version (Type "N/A" if not applicable)
      placeholder: e.g. "App 3.4.1" or "N/A"
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or information about the problem here. Type "N/A" if not applicable.
      placeholder: "N/A"
    validations:
      required: true
